use_frameworks!

platform :ios, '9.3'

target 'AsyncTimeoutOperationQueue_Example' do
  pod 'AsyncTimeoutOperationQueue', :path => '../'

  target 'AsyncTimeoutOperationQueue_Tests' do
    inherit! :search_paths

  end
end
